### ISSUE TITLE
Add Conda Lock File and Environment YAML for Project Reproducibility

### ISSUE THREAD

**Issue by AzinPiran** [UBC-MDS/airline-customer-satisfaction-predictor#6] opened 2024-11-22 18:06 UTC
To enhance the reproducibility and usability of our project, I propose adding the following files:
environment.yml
This file will specify the required dependencies and their versions, making it easier for collaborators to set up the project environment consistently across different systems.

conda-lock.yml
This file will lock exact dependency versions, ensuring that environments created from the environment.yml file are identical, even if dependency updates occur in the future.

@cs-uche , please let me know which libraries exactly you were using for your data modeling.

**Comment by cs-uche** [comment] 2024-11-22 21:16
This is a great suggestion @AzinPiran I reviewed the code and @shengjiayuu has included an environment.yml file. 
This can be used to create a conda-lock file.

**Comment by cs-uche** [comment] 2024-11-23 00:15
#11 - conda-lock.yml and environment.yml file created to enhance the reproducibility.
Please review.

I will be closing this issue since it has been resolved.

**Closed by cs-uche** 2024-11-23 00:15 UTC
